project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!slides/[0-9]*.qmd"

website:
  page-navigation: true
  title: "Supercharging Statistical Analysis with ARDs and the {cards} R Package"
  description: "2025 R/Medicine"
  favicon: "images/cards-cardx-gtsummary-hex.png"

  repo-url: https://github.com/ddsjoberg/ARD-PHUSE-talk-2025
  repo-actions: [edit, issue]

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/). Inspired by [@minecr.bsky.social](https://bsky.app/profile/minecr.bsky.social)."
    background: "#99B1C6"

  sidebar:
    background: "#99B1C6"
    logo: "images/cards-cardx-gtsummary-hex.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/Melkiades/ARD_rmedicine25
        text: GitHub
    style: docked
    contents:
     - href: index.qmd
       text: Home
     - href: license.qmd

format:
  html:
    theme: [cosmo, theme.scss]
    toc: true
    code-copy: true
    code-overflow: scroll
    mainfont: "Atkinson Hyperlegible"
    highlight-style: a11y
  
editor: source

